### ISSUE TITLE
App icon request.

### ISSUE THREAD

**Issue by yellows8** [yellows8/ctr-httpwn#1]
I want a 48x48 PNG app icon. This userland-only app is mainly intended for bypassing sysupdate-requirements, but it can be used for other things via user config as well. This also results in sysupdates being blocked from downloading normally(the system handles it the same way as if no sysupdate is available).

In the icon "httpwn" text should be included. One potential icon would be a sysupdate-download image, with an extra arrow indicating sysupdate bypass which contains the previously mentioned text. Any icon indicating sysupdate-requirement bypass with the "httpwn" text being included in the icon is fine too.

The deadline, and when this issue will be closed, is ~~around when this app gets released~~ roughly March 21, 2016, 21:00 UTC-0400.

**Comment by kershvrc** [comment]
I changed to arrow color to red to symbolize 'burning desire" and to point to the right to symbolize 'moving forward'.
/s
![httpwn](https://cloud.githubusercontent.com/assets/4391657/13907118/70f1c01c-eebd-11e5-856c-733268b4d5ee.png)
[httpwn.zip](https://github.com/yellows8/ctr-httpwn/files/181512/httpwn.zip)

Font could use work, psd in zip.

**Comment by QbeRoot** [comment]
![icon proposal](https://cloud.githubusercontent.com/assets/7386633/13907310/840b211a-eeeb-11e5-9352-14762988f331.png)

Font and text colors could change.

**Comment by yellows8** [comment]
@QbeRoot No need to have multi-color text.

**Comment by yellows8** [comment]
These icons don't really indicate any kind of "bypass" tbh(minus text itself). With "One potential icon" I meant  a sysupdate-download icon with an _extra_ arrow going around/whatever the download portion of the icon.

**Comment by 0x0ade** [comment]
My shitty attempt.

![httpwn sk 1 sm](https://cloud.githubusercontent.com/assets/1200380/13907469/29b8c092-eeef-11e5-88fb-6773743cf122.png)
(HD: https://cloud.githubusercontent.com/assets/1200380/13907470/29d298aa-eeef-11e5-95f7-c129e6ea8940.png)

Edit: Changed HD preview to link; words.

**Comment by ItsYogSothoth** [comment]
I'm shitty artist....
![httpwn](https://cloud.githubusercontent.com/assets/14014806/13907502/c85ad83e-eeef-11e5-9db1-9d8fa05dfc55.png)

**Comment by yellows8** [comment]
@0x0ade Nice.

**Comment by QbeRoot** [comment]
@yellows8 Better?

![sans titre](https://cloud.githubusercontent.com/assets/7386633/13907583/c98eca6a-eef1-11e5-979c-81d02745a855.png)

**Comment by yellows8** [comment]
@QbeRoot Indeed.

**Comment by fincs** [comment]
Warning: I am not a graphics artist.
![httpwn](https://cloud.githubusercontent.com/assets/581494/13907773/458bdb5e-eef6-11e5-9d64-1fdce59e1636.png)

**Comment by Deltios** [comment]
@yellows8 

![httpwn](https://cloud.githubusercontent.com/assets/17970387/13907839/64b00ec8-eef7-11e5-9a54-9162fc8f5a7f.png)

I like drawing, cooked this up in a few minutes~

**Comment by gocario** [comment]
I don't like drawing.
![httpwn](https://cloud.githubusercontent.com/assets/1345742/13907853/9a8aa260-eef7-11e5-8b1d-50562eeced4d.png)
![httpwn-2](https://cloud.githubusercontent.com/assets/1345742/13907854/9b1da5f6-eef7-11e5-8195-d989adf3e5b3.png)

**Comment by Daniel-Griffiths** [comment]
![icon](https://cloud.githubusercontent.com/assets/1458314/13907958/546c3cf4-eef1-11e5-9a41-9e3686e9f385.png)

How about a more minimalistic icon?

**uncompressed download:** https://dl.dropboxusercontent.com/u/13594612/Art/icon.png

**Comment by yellows8** [comment]
@Daniel-Griffiths Nice.

**Comment by hunterwolf13** [comment]
![48x48 eshop spoof](https://cloud.githubusercontent.com/assets/17970606/13908286/5b589764-eede-11e5-81a0-dde893122f56.png)
[](url) i heard you need a new eshop spoof icon
![48x48 eshop spoof](https://cloud.githubusercontent.com/assets/17970606/13908069/2c3678f6-eeda-11e5-9d90-e8fd7506cee7.png)

**Comment by Nabixlol** [comment]
I tried to make one. I'm not good with small icons. :(

![icon](https://cloud.githubusercontent.com/assets/17970641/13908177/9997d0c0-eecb-11e5-84f1-516461ec3fe9.png)

**Comment by giodude12** [comment]
![3ds spoofer](https://cloud.githubusercontent.com/assets/15522044/13908242/efc1a620-eed4-11e5-8834-86834da9da47.png)

Idk, groucho is funny

**Comment by ihaveamac** [comment]
![border](http://i.imgur.com/DtHPp8B.png) ![noborder](http://i.imgur.com/rEoHYTU.png)
went for something more simple. my idea was based on [the system update icon](http://i.imgur.com/0wsGi4F.png), with an "update" being redirected away from the console. not too sure about the color, it's easy to change.

**Comment by yellows8** [comment]
Just now updated the deadline in the initial post.

**Comment by level3tjg** [comment]
![httpwn](https://cloud.githubusercontent.com/assets/11725521/13912076/6832d8ba-ef0f-11e5-85e2-e9322e7b10ed.png)
lel I tried making a really simple grey Icon, going with the no update theme, not that great

**Comment by ghost** [comment]
@level3tjg I would make the X a little smaller as it's obscuring most of the 3ds. But its definitely looking good already.

**Comment by luigoalma** [comment]
Oh well, I'm not an artist, but at least I can say that I tried.
On the first image the colours are from the arrows themselves, but in the second they represent data in the form of a fluid.
![Image 1](https://cloud.githubusercontent.com/assets/7107338/13927154/6dff7154-ef87-11e5-8531-809cf06302f7.png)
![Image 2](https://cloud.githubusercontent.com/assets/7107338/13927179/910969b6-ef87-11e5-8add-dde0971f9735.png)

**Comment by Spatchy** [comment]
![httpwn](https://cloud.githubusercontent.com/assets/17989046/13927333/3ed54c80-ef89-11e5-8763-e11f7d7d30a1.png)

just made this if you are still accepting icon submissions! :)

**Comment by cactuspeeler** [comment]
![untitled](https://cloud.githubusercontent.com/assets/17990216/13929463/a7512144-ef70-11e5-9c05-f38de4f2f341.png)

**Comment by yellows8** [comment]
" if you are still accepting icon submissions" Of course, the final icon won't be selected until the deadline from the OP.

**Comment by DarkFlare69** [comment]
![icon](https://cloud.githubusercontent.com/assets/10453867/13934963/7323ab26-ef7a-11e5-9fcd-08de8f9ec8cb.png)

Here is my submission. It's hard to do anything with 48x48. It should be pretty self explanitory

**Comment by piersonjon** [comment]
![httpwn](https://cloud.githubusercontent.com/assets/8460978/13935658/ce500cf6-ef8e-11e5-8035-8b22c1029718.png)
Is this the image you're trying to convey?

**Comment by yellows8** [comment]
Perhaps.

**Comment by Frizouy** [comment]
Hi mine ![nintendo v1 test](https://cloud.githubusercontent.com/assets/15371270/13936682/b0dba2f0-ef95-11e5-92b1-2252e552da2e.png)
![nintendo v2 test](https://cloud.githubusercontent.com/assets/15371270/13936689/b989f0dc-ef95-11e5-8c3c-5078349d23da.png)

**Comment by yellows8** [comment]
Missing 'n'(afaict).

**Comment by yellows8** [comment]
The final icon has been selected.
