### ISSUE TITLE
Connection problem with Badge Arcade

### ISSUE THREAD

**Issue by fayer3** [yellows8/ctr-httpwn#12]
Most of the time when using Badge Arcade I get the Error-Code: 006-0501
Sometimes it starts without any problems.

I'm using ctr-httpwn 1.0.1 from the starter kit with ironhax and  hax 2.7.
I'm on firmware 10.3.0-28E

**Comment by yellows8** [comment]
Random connection errors aren't really ctr-httpwn related.

**Comment by yellows8** [comment]
FWIW I couldn't reproduce any issues with Badge Arcade on v10.5 last time I tried a while ago.

**Comment by fayer3** [comment]
Maybe it's a problem with the 10.3 firmware? I've seen peoples posts online, having the same problem with that firmware.
But thanks you have looked at this.

**Comment by fayer3** [comment]
seems to be a problem with 10.3. 
I've updated to 10.7 and didn't encounter this problem so far.
