### ISSUE TITLE
htt-pwn not working

### ISSUE THREAD

**Issue by Marctastikk** [yellows8/ctr-httpwn#20]
Is the server going to be temporarily down or do we need to find another way around? =[

**Comment by yellows8** [comment]
It's not down atm.

**Comment by Marctastikk** [comment]
It says config downloading failed. Just started doing this like 2 days ago.

**Comment by yellows8** [comment]
https://github.com/yellows8/ctr-httpwn#usage "Do not use this when the system date is not set correctly ..."

**Comment by yellows8** [comment]
#21

**Comment by Marctastikk** [comment]
Everything is set. My time and date are fine, and its still giving this error =/

**Comment by yellows8** [comment]
ctr-httpwn v1.0.1?

**Comment by Marctastikk** [comment]
Yes.

**Comment by yellows8** [comment]
It works fine here. Screenshot/whatever of your Home Menu top-screen?

**Comment by Marctastikk** [comment]
I got it!!! I knew there was a new version 1.0.1 and I thought I downloaded it 2 nights ago but apparently I did not. My apologies, but thank you tons for the replies. I'm a noob at this forgive meh lol

**Comment by Marctastikk** [comment]
I had re-downloaded the older version >_<
