### ISSUE TITLE
Server Down?

### ISSUE THREAD

**Issue by cunfricht** [yellows8/ctr-httpwn#22]
Hi,

I'm running an A9LH Luma3DS + 11.0.0-33U sysNAND o3DS. I'm trying to use ctr-httpwn for the Pokemon X/Y/OR/AS Mystery Machine, but since I've never run ctr-httpwn before it has to download the config file. However it looks like the server is down - I keep getting errors saying "httpcGetResponseStatusCode returned 0xd8a0a049 Config downloading failed." Trying to open yls8.mtheall.com in Chrome tells me that the server is down.

Not sure where else I could post this except for here just in case you didn't know.

Thanks!

**Comment by yellows8** [comment]
*mtheall.com has been down due to power outage for hours.

**Comment by etshelden** [comment]
Any chance it'll be back up soon?

**Comment by yellows8** [comment]
```
11:37:06 2016-06-12 -0400 <@yls8bot> Power to the *mtheall.com server was lost, the server may go 
                                     offline due to power-outage soon. 
11:42:31 2016-06-12 -0400 <@yls8bot> The *mtheall.com server will temporarily shutdown soon. 
```

**Comment by etshelden** [comment]
So, will it be back up at some point? I'm sorry for being whiny, I just really would like online access back on 10.7.

**Comment by yellows8** [comment]
It's just another temporary power-outage as said above...

**Comment by etshelden** [comment]
Ah, okay. Good to know, sorry about that! Any chance you can let me know when it's back up?

**Comment by yellows8** [comment]
Either try accessing the *mtheall.com site manually or join IRC #3dsdev where the bot will automatically send a {power-restored} message.
