### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by Marctastikk** [yellows8/ctr-httpwn#24]
Stuck on "downloading config"

**Comment by Marctastikk** [comment]
![image](https://cloud.githubusercontent.com/assets/19406120/17260003/f653236e-559b-11e6-96ed-70c60405a178.jpeg)

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax/issues/132#issuecomment-235899655

**Comment by Marctastikk** [comment]
What is googles dns?

**Comment by tommai78101** [comment]
@Marctastikk 

https://developers.google.com/speed/public-dns/

**Comment by Marctastikk** [comment]
I'm not sure what to put for the DNS settings. I tried 8.8.8.8 and its still not working.

**Comment by yellows8** [comment]
yellows8/browserhax_site#7

**Comment by Marctastikk** [comment]
I got everything working again. Thanks for the assistance all.
