### ISSUE TITLE
Won't return to home menu

### ISSUE THREAD

**Issue by HypeRabbit** [yellows8/ctr-httpwn#29]
11.0.0-33U, menuhax.
When I try to go to home menu (no reboot) from Homebrew Launcher, the 3DS just freezes. If I press the power button at this time, Homebrew Launcher will exit and I'll be left with the screen the 3DS shows when you press the power button, the screen asking confirmation that you want to turn off the 3DS. If I press the Home button at this time, the 3DS says "Home Menu", as if it's trying to load Home Menu, but it never loads. Pressing the Home button after the 3DS freezes on Homebrew Launcher does nothing.

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax#usage-notes-for-sdiconhax
