### ISSUE TITLE
Httpwn doesnt seem to work 

### ISSUE THREAD

**Issue by fennectech** [yellows8/ctr-httpwn#31]
i have tried re installing the hack  with the ctr-httpwn installer  but i cant get it to work   sysupdates are still prompted when doing anything online   the install appears to work    but doesnt have the desired outcome

**Comment by yellows8** [comment]
Sounds like you didn't exit to Home Menu as specified in the README ...........

**Comment by fennectech** [comment]
i did exit to home menu   ive also even rebooted the console

**Comment by fennectech** [comment]
NEVERMIND   I was stupid
