### ISSUE TITLE
Can't download config / server down

### ISSUE THREAD

**Issue by Marctastikk** [yellows8/ctr-httpwn#32]
Server down?

**Comment by pewingfield** [comment]
I'm having the same problem
`httpcGetResponseStatusCode returned 0xd8a0a049. Config downloading failed: 0xd8a0a049. An error occured. If this is an actual issue not relating to user failure, please report this to here if it persists(or comment on an already existing issue if needed), with a screenshot: https://github.com/yellows8/ctr-httpwn/issues`
Screenshot: 
![img_20161106_214739](https://cloud.githubusercontent.com/assets/6061472/20044894/c2de4c2a-a46a-11e6-97e0-1ef9643c72d3.jpg)

**Comment by yellows8** [comment]
This can't be used atm, see: https://github.com/yellows8/browserhax_site/issues/17

**Comment by xFirelent** [comment]
Same problem here

**Comment by Marctastikk** [comment]
Is the server going to be down permanently?

**Comment by geemaan** [comment]
Thanks for the hints in the browserhax_site#17 issue, I managed to successfully access the eShop using my cached server_config.xml that points to my own http server with NetUpdateSOAP.php

**Comment by Multipixelone** [comment]
I did that, But I am still getting the error 0xd9001bf7, I can access the php file, and it's just plaintext. is that what I want?

**Comment by sugiruu** [comment]
https://github.com/nevermnd/ctr-httpwn
