### ISSUE TITLE
Cant download conifg file (OLD 3DS 11.0.0.33-U)

### ISSUE THREAD

**Issue by ghost** [yellows8/ctr-httpwn#39]
![20161125_221118](https://cloud.githubusercontent.com/assets/9341192/20637919/55746594-b364-11e6-9368-c72481efa736.jpg)
I've tried downloading the config file and it wouldn't work.  I'm connected to the Internet, but no results. Any help? Also couldn't get an internal screenshot for some reason. So this is all I could get.

**Comment by sugiruu** [comment]
Servers are currently offline #32
