### ISSUE TITLE
Emunand and different regions

### ISSUE THREAD

**Issue by fwannmacher** [yellows8/ctr-httpwn#4]
Could it be used to access eShop from emunand with changed region? I mean, bypassing the error 005-5958.

**Comment by yellows8** [comment]
You're using nandredir, there's no point using this when you can just replace console-unique NAND data with data from another system.

**Comment by fwannmacher** [comment]
Could you explain how I do that? I have 2 3DS, an US one and an EU one. What kind of data I have to replace?

**Comment by yellows8** [comment]
Check gbatemp for that.

**Comment by fwannmacher** [comment]
Thanks
