### ISSUE TITLE
Downloading config failed.

### ISSUE THREAD

**Issue by MattLuu01** [yellows8/ctr-httpwn#43]
![unnamed](https://cloud.githubusercontent.com/assets/17915764/20998097/58b5d3ea-bcd9-11e6-847f-377b6b0bf016.jpg)

**Comment by MattLuu01** [comment]
I'm on n3DS 11.0.0

**Comment by oniietzschan** [comment]
Funny, after trying this dozens of times over the course of 36 hours (Including many config mirrors and such) I finally got this to work riiiiight before was about to get fed up and comment here as well.

So keep at it. For your own information, I got it working using the an unmodified v1.0.1 release from this repository. I'm on 11.0.0-33U.

**Comment by yellows8** [comment]
Works fine here FWIW. https://www.3dbrew.org/wiki/HTTP_Services#Error_codes

**Comment by MattLuu01** [comment]
Oh nvm I fixed it. I had my proxy on.
