### ISSUE TITLE
The installed HTTP sysmodule version (v12288) is not supported.

### ISSUE THREAD

**Issue by 0ICED0** [yellows8/ctr-httpwn#44]
so a solution to this will be updating my HTTP sysmodule?
![img_20161226_185038658](https://cloud.githubusercontent.com/assets/24785030/21489210/9afbb5b8-cb9c-11e6-9513-51803b84b81b.jpg)

**Comment by yellows8** [comment]
Or just install sysupdate >=v9.6 .....

**Comment by 0ICED0** [comment]
im on 9.2

**Comment by 0ICED0** [comment]
ok this was caused by a partial downgrade.
