### ISSUE TITLE
New version available? (0xfffffffb)

### ISSUE THREAD

**Issue by WeepingWalrein** [yellows8/ctr-httpwn#48]
Opening ctr-httpwn for the first time, I got invalid statuscode: 500 when attempting to download config. Error code "Config downloading failed: 0xfffffffb"

Server reply: "The server release_version doesn't match the application release_version. A new version of ctr-httpwn is likely available." 

Is this true? If so, where can I find the updated version? My version shows v1.0.1. My system is 11.2.0-35U. I have shut down and rebooted my system a few times now, and I still get the same error. Where have I gone wrong?

**Comment by yellows8** [comment]
...... https://github.com/yellows8/ctr-httpwn/releases

**Comment by WeepingWalrein** [comment]
Thank you! I could not find that tab before.
