### ISSUE TITLE
v1.2 not working

### ISSUE THREAD

**Issue by Oyomar** [yellows8/ctr-httpwn#49]
It is saying *hax payload >=v2.8 is required
Reboot your system and try again
Haxx setup failed: 0xd8e06406

I tried rebooting but it didn't work.

Thanks,

**Comment by Oyomar** [comment]
Or is that supposed to happen? I tried going online and trading via Pokemon Moon and apparently it works. Even the Nintendo eShop works.

**Comment by yellows8** [comment]
Rebooting your system isn't going to install latest *\hax payload .......

That's only for bosshaxx, which you can ignore since you're not using that.
