### ISSUE TITLE
Haxx setup failed: 0xffffffff

### ISSUE THREAD

**Issue by MightyMathos** [yellows8/ctr-httpwn#52]
Hello there! I keep getting this error when trying to use this. Im on 11.2 with luma3ds/a9lh booting ctrhttpwn1.2 via homebrew loader.

**Comment by yellows8** [comment]
Make sure you're using the official release & not modified versions.

**Comment by MightyMathos** [comment]
I just downloaded it from here, the latest release is the official one right?

**Comment by yellows8** [comment]
Yes, dunno then.

**Comment by NarryG** [comment]
I'm getting the same issue. Using the latest official release.

**Comment by MightyMathos** [comment]
Maybe its because of this? Read it in the readme. " When new sysupdates are released, the yls8.mtheall.com site will automatically determine all of the new version values to use with network services. This may take a little while after sysupdate release to finish, hence the server will return error messages until it's done(which is at the same time that the updatedetails text for the ninupdates report becomes available)." It would make sense for the most part with 11.3 just being released.

**Comment by yellows8** [comment]
That's been done.

**Comment by NarryG** [comment]
The updatedetails text has been done for a while. That's why I reaffirmed that it was an issue for more than one person and was still happening as of five minutes ago

**Comment by MightyMathos** [comment]
Oh well then idunno.

**Comment by NarryG** [comment]
Here's the full error message by the way. Probably don't need it but just in case it tips you off as to what might be causing it,
![2017-02-06 23 18 19](https://cloud.githubusercontent.com/assets/3047793/22677711/ce3c2dda-ecc2-11e6-8db8-428f8986122f.jpg)

**Comment by yellows8** [comment]
Works fine here.

**Comment by NarryG** [comment]
Are you telepathic. I literally just checked 30 seconds ago (still not working for me, same error. Running the latest version from the release section) and I get a notification from Github that it's working on your end the moment I see it's still failing for me (n3ds, 11.2, latest stable luma). I'll fiddle around with it and try again tomorrow if it still fails.

**Comment by NarryG** [comment]
I just shut off forcing N3DS Clock + L2 Cache in my Luma settings and it worked fine. Turned it back on  the error is back. This is Luma 6.6 stable

Edit: Just forcing the N3DS Clock works fine. Seems to be L2 Cache breaking it
Edit 2: Forcing only L2 cache with no clock throws the error.

**Comment by Liger0** [comment]
I'm having errors too. I receive [this](http://i.imgur.com/PbsF7nl.jpg) using clock+l2 and [this](http://i.imgur.com/039Pfw4.jpg) using only clock in Luma.
I have the hax 2.7 and I really don't understand how to update it, I used the same files and procedure for sysnand and emunand but I have 2.7 in sysnand and 2.8 in emunand.

**Comment by judiaz11** [comment]
Just tried running it on an O3DS XL and a N3DS XL both on 11.2 using the same ctr-httpwn folder that was available from the homebrew starter kit yesterday and got similar results to danne2. The O3DS XL was able to use the hax on the first try, but the N3DS would returned the error until I turned off Clock + L2 Cache.

**Comment by alexisbietti** [comment]
Didn't work for me on N3DS 11.2 with Clock + L2 cache off. Latest release downloaded from here a few minutes ago. Cheers.

**Comment by NarryG** [comment]
What was the error? Was it 0xffffffff? Are you sure you don't have a custom URL file from a previous version?

**Comment by Majickhat55** [comment]
Yeah turning off the L2 cache works. Thanks for the tip. Also as a bonus it made HANS work with Pokemon SuMo as well, if anyone cares.

**Comment by mshipman** [comment]
Confirmed L2 cache off (clock on or off) fixes the issue in Luma (latest commit).

**Comment by MightyMathos** [comment]
Thank you!

**Comment by yellows8** [comment]
Due to the comments from here: https://github.com/yellows8/ctr-httpwn/commit/9a3a14310bf993614e6811f2cad2506cc39dfbe4
