### ISSUE TITLE
Latest version doesn't work.

### ISSUE THREAD

**Issue by nanashi89** [yellows8/ctr-httpwn#54]
"svcMapMemoryBlock with the httpheap sharedmem failed: 0xd9001bf7. Haxx setup failed: 0xd9001bf7."

I'm on the Luma3DS firmware, btw, have not upgraded to the latest OFW.

**Comment by yellows8** [comment]
https://github.com/yellows8/ctr-httpwn#usage "Do not run this app more than once when ctr-httpwn is already active under the sysmodule."

**Comment by nanashi89** [comment]
Doesn't it deactivate once you go to the options menu? Or use that custom microSD management CIA? 
It works now, anyway (turned my N3DS off and on again), but I thought after using one or the other, it would deactivate.
