### ISSUE TITLE
[SOLVED] Non-CFW 3DS 11.2 : bosshaxx issue, won't let me connect to eShop, etc

### ISSUE THREAD

**Issue by FrankerQ** [yellows8/ctr-httpwn#55]
Using the recent  ctr-httpwn v1.2 and I get an error message saying:
WARNING: bosshaxx wasn't setup, likely due to incompatible system-version. test_boss() will not be run.

When I connect to eShop, I get a different kind of error message saying that there is a software update by going to the system settings. There wasn't even a button shortcut that takes the user to the settings menu.

Any reasons why and possible solutions?
3DS version: 11.2.0.35 - E

![00181](https://cloud.githubusercontent.com/assets/25872544/23097701/a0d9b79e-f632-11e6-9951-f23fd85ab161.png)

.

**Comment by yellows8** [comment]
"Using URL loaded from ..." <- Delete that file.

**Comment by FrankerQ** [comment]
Thank you. This has solved my problem :D
