### ISSUE TITLE
Error code 0xffffffff

### ISSUE THREAD

**Issue by KingJangy** [yellows8/ctr-httpwn#58]
I`m on 11.3 with a9lh and luma3ds but it will not work :(
![img_20170411_195654 2](https://cloud.githubusercontent.com/assets/27338193/24947335/b46b4b8a-1f66-11e7-9a78-ccbbdccb3fa1.jpg)
![img_20170411_195737 1](https://cloud.githubusercontent.com/assets/27338193/24947343/ba83a364-1f66-11e7-8f47-5799308928cd.jpg)
![img_20170411_195604 1](https://cloud.githubusercontent.com/assets/27338193/24947317/a5834406-1f66-11e7-9d1f-9a437a9a9505.jpg)

**Comment by Real96** [comment]
I've got the same problem

**Comment by destinedjagold** [comment]
I have the same problem as well. Using the latest release of ctr-httpwn and my n3dsXL's FW is 11.3

**Comment by RocketRobz** [comment]
I too, also have the same issue.
Using ctr-httpwn v1.2, and my N3DSXL FW is also 11.3.

**Comment by RocketRobz** [comment]
I found out why the error occurs.
You have to turn off New 3DS CPU in Luma settings to fix the issue.
I can confirm it works, as I'm no longer getting the System Update message when using eShop, Miiverse, etc.

**Comment by destinedjagold** [comment]
@Robz8 Thanks! Can confirm that it works!

**Comment by KingJangy** [comment]
@Robz8 Thank you :)

2017-04-13 7:27 GMT+02:00 destinedjagold <notifications@github.com>:

**Comment by yellows8** [comment]
https://github.com/yellows8/ctr-httpwn#usage
