### ISSUE TITLE
Config download fail

### ISSUE THREAD

**Issue by Jibaku1** [yellows8/ctr-httpwn#6]
Upon running the app, I received the following message after attempting to download the config

"httpcGetResponseStatusCode returned 0xd8a0a03c
Config downloading failed:  0xd8a0a03c
An error occured. If this is an actual issue not related to user failure, please report this to..."
etc etc

HBL is on 2.6
Firmware is 10.5.0-30U o3ds

**Comment by yellows8** [comment]
Didn't notice this issue until after fixing it, heh.
