### ISSUE TITLE
Haxx setup failed: 0xd8e06406

### ISSUE THREAD

**Issue by filippo00** [yellows8/ctr-httpwn#61]
Sys 11.2.0-35E

**Comment by RocketRobz** [comment]
Do you have Luma CFW?

**Comment by filippo00** [comment]
Yes

**Comment by RocketRobz** [comment]
Is New 3DS CPU off in Luma settings?

**Comment by filippo00** [comment]
I nave o3ds

**Comment by filippo00** [comment]
*have

**Comment by RocketRobz** [comment]
You can edit your post, by clicking the pencil icon.

Does eShop still work after the error?
