### ISSUE TITLE
haxx setup failed: 0xc920181a

### ISSUE THREAD

**Issue by saijm4444** [yellows8/ctr-httpwn#66]
After running ctr-httpwn, and BOSShaxx is triggered and a few lines like 
..
..
..
..
 appear, I get the error I mentioned in the title? What's causing the problem?

**Comment by saijm4444** [comment]
Additionally, i cannot access the eshop, and no internet services in essence. I think this happened after FBI failed to download a title via QR code.
Also, the error describes as
bossGetTaskState returned 0xc920181a 
Reboot your system then try again
Haxx setup failed: 0xc920181a 
This error means the http sysmodule crashed.

Needless to say I've restarted many times. Also, I'm running ctr httpwn 1.2

**Comment by yellows8** [comment]
sysver?

**Comment by saijm4444** [comment]
11.3
I've gotten it working again by restoring a Nand backup
No worries :)
