### ISSUE TITLE
Doesn't work on smash 3ds

### ISSUE THREAD

**Issue by RadiantDerg** [yellows8/ctr-httpwn#7]
o3ds 10.5.0-30U, using the latest release of ctr-httpwn, when I load smash bros 3ds, it still displays an error when connecting to update system

**Comment by yellows8** [comment]
Be more specific.

**Comment by RadiantDerg** [comment]
okay, I start the system, Cold booting into Menuhax. and I launch ctr-httpwn, get the latest config. return to the HB menu, exit to home menu, and then launch super smash bros 3ds. as soon as it loads, and I try to go online, it says system update is required, yet if I go to eshop, it works just fine.

**Comment by yellows8** [comment]
"o3ds" "smash 3ds" Not possible to do anything about it due to Old3DS doing a firm-boot for that: "Once run successfully, ctr-httpwn will persist under the sysmodule until the sysmodule is terminated(shutdown/reboot/**firm-boot**)."
