### ISSUE TITLE
error downloading config 0xfffffffb

### ISSUE THREAD

**Issue by abbie99** [yellows8/ctr-httpwn#72]
hi, i'm using soundhax on my 2ds on 11.3 and i've tried rebooting my console a few times but it keeps coming up with the same error - do i need to update the version of ctr-httpwn? thanks
![scr_1_top_left](https://cloud.githubusercontent.com/assets/28743174/26132042/72a72d78-3a95-11e7-8276-c7f2f8b493ec.png)

**Comment by yellows8** [comment]
https://github.com/yellows8/ctr-httpwn/releases
