### ISSUE TITLE
Update to support boot9strap v1.2+Luma3DS v8.0

### ISSUE THREAD

**Issue by KunoichiZ** [yellows8/ctr-httpwn#75]
Launching ctr-httpwn either results in a crash dump (for me) or, when using [this](https://github.com/fincs/new-hbmenu), the app loads, but the it spits out [this](https://imgur.com/a/tYBPg).

**Comment by yellows8** [comment]
"crash dump" ?

"or, when  ..." #74

**Comment by KunoichiZ** [comment]
Sorry, [here](https://www.mediafire.com/?lmwamqg4f6w3f7k) are the dumps.

**Comment by IryokuHikari** [comment]
Hello, I just updated to boot9strap v1.2+Luma3DS v8.1 and I am having the same issue that KunoichiZ is having, same error screen, same error number. 

I tried running ctr-httpwn 1.2 while simultaniously running boot-ntr 3.5, but I got a crash dump (which I did not read to see where they were). I tried running ctr-httpwn before opening boot-ntr 3.5, and I got the aforementioned error screen, as posted by KunoichiZ.

**Comment by TomG-Official** [comment]
Yup i have the same issue

**Comment by ZenythFactor** [comment]
i'm staying in 11.3 due to the issues i've heard about ctr-httpwn
hopefully there will be a fix soon before another firmware hits

**Comment by fincs** [comment]
Since you have Luma, why not just upgrade to 11.6? There is no reason to stay on an old system version.

**Comment by ihaveamac** [comment]
an irrational fear of Nintendo adding anti-cfw stuff which won't happen.

**Comment by KunoichiZ** [comment]
I haven't updated because I have no reason to. I don't play online games. For me, it's not a fear of Nintendo adding anything. It's because I have no reason to. Don't assume everyone has that as an irrational fear, @ihaveamac.

**Comment by fincs** [comment]
Not having a reason to is not a reason not to.

**Comment by KunoichiZ** [comment]
@fincs And your point is? I don't have to have my system on the latest firmware if I don't want it to. No one can tell me to update my system. If I don't use the eShop often or play online games, I have no reason to update my system.

**Comment by ihaveamac** [comment]
not having a reason to update is not the same as intentionally staying behind.

**Comment by KunoichiZ** [comment]
Does it really matter? No. I'm on a lower firmware. Oh well. I don't care. I'll update when I want to or when I have to, not when someone tells me to.

**Comment by ihaveamac** [comment]
which is fine. but it doesn't mean people need to keep supporting it.
