### ISSUE TITLE
Says FW not supported

### ISSUE THREAD

**Issue by swampingo** [yellows8/ctr-httpwn#78]
I have used this program several times on my 3ds(FW is 11.4 ) and now it says this error.

Loading+parsing internal_config.xml. . . 
downloading config . . .
The installed HTTP sysmodule version (v14336) is no
t supported. The sysmodule versionmust be the one
from system-version >=9.6.0-X.
An error occured. If this is an actual issue not r
elated to user failure. please report to here
  if it persists go to this website

I'm not sure what to do here

**Comment by yellows8** [comment]
What 3DS model exactly? EDIT: nvm

**Comment by yellows8** [comment]
https://github.com/yellows8/ctr-httpwn#supported-sysmodule-versions

**Comment by swampingo** [comment]
New 3ds

**Comment by swampingo** [comment]
xl
