### ISSUE TITLE
error since I'm on 11.5

### ISSUE THREAD

**Issue by chocos222** [yellows8/ctr-httpwn#80]
Hi, Since I'm on luma 8 and sysNand 11.5, ctr-httpwn 1.2 don't work and I have this message:
[ctr-httpwn v1.2 by yellows8.
Loading+parsing internal_config.xml
Downloading config...
The installed HTTP sysmodule version(v14336) is not supported. The sysmodule version must be the one from system-version >=9.6.0-X.
An error occured. If this is an actual issue not related to user failure, please report this to here if it persists(or comment on an already existing issue if needed), with a screenshot: https://github.com/yellows8/ctr-httpwn/issues
Press the START button to exit.]

**Comment by yellows8** [comment]
"11.5"
