### ISSUE TITLE
Error code 0xd8a0a046 on 9.4.0-21U O3DS

### ISSUE THREAD

**Issue by Bunistalri** [yellows8/ctr-httpwn#82]
So I was trying to find a way to get the acnl Welcome Amiibo update on my Soundhax NA/US 9.4.0-21U O3DS to hack Welcome Amiibo towns with the macrobledo Save Editor (without being forced to update to 11.5), and someone told me to run httpwn and then launch the eshop. I tried to run ctr-httpwn v1.2 and got this screen every time. Any way to fix this? (I'm really new to hacking sorry)

![image1 14](https://user-images.githubusercontent.com/31881163/30314864-eb8d74b8-9756-11e7-88cd-f92cd5a553b6.JPG)

This is what the homebrew launcher menu looks like:
![image1 20](https://user-images.githubusercontent.com/31881163/30315580-4e91bda6-9759-11e7-8d19-6f06ab069660.JPG)

**Comment by fincs** [comment]
Since you are on 9.4, there's no reason why you shouldn't be able to install b9s and Luma3DS (which is a quick and brickproof process). WIth it, you can actually be on the latest system version and have full & unpatchable homebrew access.

**Comment by Bunistalri** [comment]
So the only way to fix this is to get cfw? Is there any way to fix this error without cfw? (Not a tech person but I'm still curious as to why this error is happening too)
If that's the only option, what's the risk of getting hit by the 3DS banwave if I do get cfw? <-- (that's my main reason for not getting cfw, 2nd being how complicated the process looks, 3rd being that ↓↓)

Almost every hacking forum I've went to just threw this at me https://3ds.guide/ and then completely ignored me after and it's getting really tiring.

**Comment by fincs** [comment]
On your system version, installing b9s is an extremely easy process that takes less than five minutes. You won't get banned or bricked if you actually follow the steps in the guide and don't install or play illegally copied games, especially before those games are officially released.

**Comment by Bunistalri** [comment]
Figured out the issue. ctr-httpwn was throwing this error because my wi-fi switch was off. It also doesn't work on firmwares lower than or equal to 9.6.0-X and mine is on 9.4.0-X. Whoops, my bad there. Closing issue now.
