### ISSUE TITLE
HTTP sysmodule version is not supported

### ISSUE THREAD

**Issue by mar1us86** [yellows8/ctr-httpwn#84]
Hi I got an error...I followed the Soundhax guide to hack my 3ds.

ctr-httpwn v1.2 by yellows8.
Loading+parsing internal_config.xml...
Downloading config...
The installed HTTP sysmodule version(v14336) is not supported. The sysmodule version must be from system-version >=9.6.0-X.

screencapture:
![error](https://user-images.githubusercontent.com/32104616/30602955-ccd9768e-9d6e-11e7-8658-7005ce46a029.jpg)

**Comment by yellows8** [comment]
https://github.com/yellows8/ctr-httpwn#supported-sysmodule-versions

**Comment by mar1us86** [comment]
How is this possible? ...since I had version 11.0.0. before I started soundhax?!

**Comment by yellows8** [comment]
Maybe try entering recovery-mode & immediately exit.
