### ISSUE TITLE
Error code: 005-4320 (Eshop) 

### ISSUE THREAD

**Issue by Dozuken** [yellows8/ctr-httpwn#9]
Basically yesterday ctr-httpwn worked perfectly in the eshop  (although it didnt work for pokemon and smash online)  but now when i use it (activate the ctr-httpwn from the hb and returning home with start and  X) and enter the eshop i keep getting an error code 005-4320. Is anyone else getting it?

**Comment by yellows8** [comment]
Are you using ctr-httpwn v1.0.1?

**Comment by Dozuken** [comment]
In homebrew it displays ctr-httpwn v1.0
Is it a very recent update to fix that problem?

**Comment by yellows8** [comment]
https://github.com/yellows8/ctr-httpwn/releases

**Comment by Dozuken** [comment]
Alright i will try updating then
Thank you
By the way do you know if theres a high risk of nintendo banning me for using this method?

**Comment by yellows8** [comment]
I don't know if they'll ever ban systems using this.
