### ISSUE TITLE
Error Code 0xd8a0a03c

### ISSUE THREAD

**Issue by kerbmario** [yellows8/ctr-httpwn#95]
I have this error every time i want to install CTR-HTTPWN. I use a New3DS with fw 11.14.0.46E

**Comment by ShadowLugia111** [comment]
ctr-httpwn isn't compatible with 11.14.0-X; only 9.6.0-X to11.3.0-X are supported.

**Comment by xdmcwaxiest** [comment]
Im on firmware 9.6.0-24E but im still getting the same error code.

**Comment by xdmcwaxiest** [comment]
I'm on fw 11.3 and i'm still getting the same error.

**Comment by ihaveamac** [comment]
#96 - This happens because the 3DS can't download a configuration file anymore due to mtheall.com requiring a newer TLS version than the 3DS supports.

**Comment by ZenythFactor** [comment]
Any workarounds?

**Comment by ihaveamac** [comment]
There is no "workaround" to use this on newer versions. You have to find other methods.
