### ISSUE TITLE
[0xd8a0a03c] Unable to download the configuration file

### ISSUE THREAD

**Issue by TheCoder55** [yellows8/ctr-httpwn#96]
Hi, I have trouble running ctr-httpwn on my 3DS, each time I want to download the configuration file, it fails with the error 0xd8a0a03c.
My 3DS is running on the 9.6 Firmware and was able of using the cached configuration file until a new system update arrived.
By looking at the update URL (https://yls8.mtheall.com/ctr-httpwn/NetUpdateSOAP.php), I saw the following message 
"Unrecognized SOAPAction header, it probably wasn't set correctly." which would mean the update information couldn't be retrieved from Nintendo Servers.

**Comment by yellows8** [comment]
3DS uses outdated TLS which mtheall.com doesn't allow anymore.

Why haven't you updated your system?
