### ISSUE TITLE
0xd8a0a03c

### ISSUE THREAD

**Issue by Stainless34** [yellows8/ctr-httpwn#97]
I have my old 2ds System updatet  to 11.17.0 50E and just homebrewed it and when I try to download the config i get the message down below, I tried with universal update to update everything but the issue stayed. Please help me.

httpcGetResponseStatusCode returned 0xd8a0a03c
Config downloading failed: 0xd8a0a03c
An error occured. If this is an actual issue not related to user failure, please report this to

**Comment by yellows8** [comment]
#96

What are you attempting to use httpwn for?(also this build doesn't support latest sysver anyway)

**Comment by Stainless34** [comment]
I want to use the shop, is there an alternative option for me?

**Comment by yellows8** [comment]
There's no need to use httpwn for accessing eShop when you're on latest sysver?

**Comment by Stainless34** [comment]
I want to use you eshop but every time I try my ds crashes and shutdown after pressing a button
